# Blog settings
permalink: /blog/:title.html
host: 0.0.0.0

# My variables
name: YSMull
description: YSMull的个人博客
baidu_verification: false
comments: false

timezone: +0800

# File management
include: [".htaccess"]
exclude: ["README.md", "assets/node_modules/", "assets/entry.js", "assets/webpack.config.js", "assets/css/"]

author:
    name: 简单小煜
    email: ysmull@aliyun.com
    link: ysmull.cn
future: true
# Sass
# sass:
#   style: :compressed
#   sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  auto_ids:       true
  auto_id_prefix: 'id-'
  toc_levels:     '2,3'
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  # input: GFM
#   hard_wrap: false
# highlighter: rouge

collections:
   pages:
     output: true
     permalink: /:path/
