# Blog settings
permalink: /blog/:title.html
# host: 0.0.0.0

# My variables
name: YSMull
description: YSMull的个人博客
baidu_verification: false

#timezone: Asia/Shanghai
timezone: +0800

# File management
exclude: [
  ".idea/*",
  "README.md",
  "assets/yarn.lock",
  "assets/node_modules/",
  "assets/entry.js",
  "assets/webpack.config.js",
  "assets/css/",
  "assets/plugins",
  "assets/package.json",
  "assets/font",
  "./upload.sh",
  "CNAME"
]
include: [
  "assets/build",
  "assets/js"
]

author:
  name: 简单小煜
  email: ysmull@aliyun.com
  link: ysmull.cn
future: true
# Sass
# sass:
#   style: :compressed
#   sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  syntax_highlighter: none
  math_engine: mathjax
  auto_ids:       true
  auto_id_prefix: 'id-'
  toc_levels:     '2,3,4'
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: true
  syntax_highlighter_opts:
    disable: true
    # syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    # css_class: 'acc'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
# highlighter: rouge

collections:
  pages:
    output: true
    permalink: /:path/

url: "https://ysmull.cn"
plugins:
  - jekyll-sitemap
  - jekyll-feed
#  - jekyll-katex

feed:
  path: atom.xml
