markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title.html
paginate: 10
author: 
    name: 简单小煜
    email: maoyusu@outlook.com
    link: www.mathao.com

title: 简单小煜
subscribe_rss: /pages/atom.xml
gems: [jekyll-paginate]

